### ISSUE TITLE
Weird Crash

### ISSUE THREAD

**Issue by Spazmunki13** [elytra/BitHop#1]
I get this crash with your mod for some reason, removing your mod fixes the crash. I have forgelin 1.6.0 and BitHop 1.0.1. Playing on MC 1.12.2 with forge 14.23.2.2634.

https://openeye.openmods.info/crashes/8e287d6907d62ea3eb6e92e1e2d3a1af

EDIT: Crash happens when loading the game.

**Comment by LemmaEOF** [comment]
oh boy.

**Comment by LemmaEOF** [comment]
ok I found the issue, I need to learn how to do dependencies

**Comment by LemmaEOF** [comment]
uh apparently it didn't fix it???? I'm gonna have @NikkyAI poke at it to see what I'm doing wrong

**Comment by LemmaEOF** [comment]
Use v1.0 for now, it doesn't fail on launch if you're missing forgelin but otherwise it's just fine

**Comment by LemmaEOF** [comment]
it's finally fixed! Dependency version notation is weird.
