### ISSUE TITLE
Crash due to "java.lang.IllegalArgumentException: Parameter specified as non-null is null"

### ISSUE THREAD

**Issue by kd8lvt** [elytra/BitHop#5]
Simple Grinder => Vanilla Hopper => BitHop => Vanilla Furnace
Causes crash when an item goes through the system from the Simple Grinder

Not sure who is at fault here, but most of the crash log references BitHop, so I'm going out on a limb to say it's probably you guys.
[Crash Log](https://pastebin.com/xbRT6rNU)

The affected world constantly crashes now.

Image of the setup : 
![image](https://user-images.githubusercontent.com/5531395/38747331-872227b6-3f18-11e8-824d-0f9cb9f48000.png)

**Comment by LemmaEOF** [comment]
I just got back from vacation, so I'll take a look as soon as possible.

**Comment by LemmaEOF** [comment]
It looks like some bad java code is interacting poorly with our Kotlin. I'm gonna have @alexbobp take a look at it, and we'll get a fix out ASAP.

**Comment by LemmaEOF** [comment]
We just did a pretty big refactor and I wanna see if it changed anything. @kd8lvt, can you try out [this](https://ci.elytradev.com/job/elytra/job/BitHop/job/master/lastSuccessfulBuild/artifact/build/libs/BitHop-master-1.46.jar) build of BitHop and see if it changes anything?

**Comment by kd8lvt** [comment]
Will do! Give me a moment...

**Comment by LemmaEOF** [comment]
@kd8lvt any luck?

**Comment by kd8lvt** [comment]
Sorry about the delay, my power went out after an ice storm, (yay northern latitudes) and I've been having issues with my computer since. Anyhow, I got it working, and the link doesn't work now, but messing around with the URL I found 1.4.9, and now the Hopper won't push into the BitHop.

**Comment by LemmaEOF** [comment]
I'm afraid I'm not having any luck reproducing this, sorry.

**Comment by kd8lvt** [comment]
Hrm... sorry to have wasted time, should I close the issue, or leave it for now?

**Comment by LemmaEOF** [comment]
I'll leave it open and tinker with it. It might be something to do with Diet Hoppers, in which case I'm not sure there's much I can do about it.

**Comment by kd8lvt** [comment]
Ah, Diet Hoppers would make sense. Alrighty then, leaving this open for future reference. The hopper not pushing is really odd though. I never tried pushing from any other side, probably would have been smart of me. Ah well, it's getting late, and I have work in the morning. I'll try pushing from other sides when I get home from work.

**Comment by kd8lvt** [comment]
Bug resolved with newest version of Forge and BitHop.

**Comment by exaskye** [comment]
Yeah, this got fixed in d2bdf89c. We forgot to close the issue.
