### ISSUE TITLE
Crash when placing bithop on the side of Charset Storage barrel or Faucets and Filters Pipe

### ISSUE THREAD

**Issue by stohun01** [elytra/BitHop#6]
works fine when placed on the back or top of a barrel, but the front or sides causes a crash.
[crash report](https://pastebin.com/GpYJJyfv)

Similar issue with pipes from Faucets and Filters
[crash report](https://pastebin.com/25jUASys)

**Comment by LemmaEOF** [comment]
Found what's up. I know exactly what's happening, so it should be an easy fix. TL;DR, we accidentally made it throw when there's a null CapabilityItemHandler instead of just return, which is what it should do.

**Comment by andylizi** [comment]
Would you mind releasing a new version for the fix? I've also encountered this issue, and then discovered that this problem has been fixed two years ago....
```
java.lang.NullPointerException: Ticking block entity
	at com.elytradev.bithop.tile.TileEntityBitHop.activateHopper(TileEntityBitHop.kt:19)
	at com.elytradev.bithop.tile.TileEntityBaseHop.func_73660_a(TileEntityBaseHop.kt:41)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

---

Anyway, I compiled a version `1.2.1` myself, based on the latest commit db44bdc363eeaebfc530ce182c167922ee54c13b (with [Concrete](https://github.com/elytra/Concrete) bumped to [`0.4.45`](https://repo.elytradev.com/com/elytradev/concrete/concrete-common/) and some modifications to the gradle file for it to build correctly). **Here's the jar for others who are interested**: [_BitHop-70db647-1.2.1.67.zip_](https://github.com/elytra/BitHop/files/4873678/BitHop-70db647-1.2.1.67.zip)

The exact modifications are detailed below:
```diff
diff --git a/build.gradle b/build.gradle
index 6b710db..c0fb2a1 100755
--- a/build.gradle
+++ b/build.gradle
@@ -144,7 +144,7 @@ if (needsShadow) {
                shadowJar { mappingType = 'SEARGE' }
        }

-       tasks.reobfJar.doLast {
+       tasks.reobfShadowJar.doLast {
                file('build/libs/'+archivesBaseName+'-'+version+'-slim.jar').delete()
        }

diff --git a/project.gradle b/project.gradle
index 05d864c..4227e1d 100755
--- a/project.gradle
+++ b/project.gradle
@@ -5,9 +5,9 @@ ext {
        projectName = 'BitHop'

        useElytraVersionFormat = true
-       version = '1.2'
+       version = '1.2.1'

-       concreteVersion = '0.3.7-SNAPSHOT'
+       concreteVersion = '0.4.45'
        concreteModules = [ 'common', 'inventory', 'recipe', 'config' ]

        coremod = null
```
